import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';

type Post = { id: string; title: string; body: string; status: string; created_at: string; view_count: number; category_id: string | null; categories: { name: string } | { name: string }[] | null };
export default async function PostsPage({ searchParams }: { searchParams: Promise<{ q?: string; category?: string; tag?: string; sort?: string }> }) {
  const { q = '', category = '', tag = '', sort = 'latest' } = await searchParams; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect('/login');
  const { data: membership } = await supabase.from('organization_members').select('organization_id').eq('user_id', user.id).eq('status', 'approved').limit(1).maybeSingle(); if (!membership) return <main className="onboarding"><section className="onboarding-card"><h1>Join a workspace first</h1><Link className="primary" href="/workspace">Open workspace</Link></section></main>;
  const { data: categoryRows } = await supabase.from('categories').select('id, name').eq('organization_id', membership.organization_id).order('name'); const { data: tagRows } = await supabase.from('tags').select('id, name').eq('organization_id', membership.organization_id).order('name');
  let query = supabase.from('posts').select('id, title, body, status, created_at, view_count, category_id, categories(name)').eq('organization_id', membership.organization_id); if (category) query = query.eq('category_id', category); const { data: rows } = await query.order(sort === 'views' ? 'view_count' : 'created_at', { ascending: false });
  let posts = (rows ?? []) as unknown as Post[]; if (tag) { const { data: tagged } = await supabase.from('post_tags').select('post_id').eq('tag_id', tag); const ids = new Set((tagged ?? []).map((row) => row.post_id)); posts = posts.filter((post) => ids.has(post.id)); }
  const normalized = q.trim().toLowerCase(); if (normalized) posts = posts.filter((post) => `${post.title} ${post.body}`.toLowerCase().includes(normalized)); const { data: likeRows } = posts.length ? await supabase.from('likes').select('post_id').in('post_id', posts.map((post) => post.id)) : { data: [] }; const likeCounts = new Map<string, number>(); (likeRows ?? []).forEach((like) => likeCounts.set(like.post_id, (likeCounts.get(like.post_id) ?? 0) + 1)); if (sort === 'likes') posts.sort((a, b) => (likeCounts.get(b.id) ?? 0) - (likeCounts.get(a.id) ?? 0));
  return <main className="workspace-page"><header className="workspace-header"><Link className="brand" href="/"><span className="brand-mark">W</span><span>workhub</span></Link><div><strong>Knowledge</strong><small>Organization posts</small></div><Link href="/workspace" className="back-link">Workspace</Link></header><section className="workspace-content"><div className="workspace-intro"><p className="eyebrow"><span /> KNOWLEDGE</p><h1>Share what your team knows</h1><Link className="primary" href="/posts/new">Write post</Link></div><section className="workspace-panel"><form className="task-form" action="/posts"><label htmlFor="search">Search</label><input id="search" name="q" defaultValue={q} /><label htmlFor="category">Category</label><select id="category" name="category" defaultValue={category}><option value="">All categories</option>{(categoryRows ?? []).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><label htmlFor="tag">Tag</label><select id="tag" name="tag" defaultValue={tag}><option value="">All tags</option>{(tagRows ?? []).map((item) => <option value={item.id} key={item.id}>#{item.name}</option>)}</select><label htmlFor="sort">Sort</label><select id="sort" name="sort" defaultValue={sort}><option value="latest">Latest</option><option value="views">Most viewed</option><option value="likes">Most liked</option></select><button className="primary">Apply</button></form><div className="workspace-panel-title"><h2>Posts</h2><span>{posts.length}</span></div><div className="live-tasks">{posts.map((post) => { const categoryValue = Array.isArray(post.categories) ? post.categories[0] : post.categories; return <Link className="live-task" href={`/posts/${post.id}`} key={post.id}><div><b>{post.title}</b><small>{post.status} · {categoryValue?.name || 'No category'} · {post.view_count} views · {likeCounts.get(post.id) ?? 0} likes</small></div></Link>; })}</div></section></section></main>;
}
