import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { createTask, setTaskStatus } from '@/app/workspace/actions';

type Task = { id: string; title: string; priority: string; status: 'todo' | 'in_progress' | 'done'; due_at: string | null; labels: string[] | null };
const columns: Array<{ key: Task['status']; title: string }> = [{ key: 'todo', title: 'To do' }, { key: 'in_progress', title: 'In progress' }, { key: 'done', title: 'Done' }];

export default async function TasksPage({ searchParams }: { searchParams: Promise<{ priority?: string; deadline?: string }> }) {
  const { priority = '', deadline = '' } = await searchParams; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect('/login');
  const { data: membership } = await supabase.from('organization_members').select('organization_id').eq('user_id', user.id).eq('status', 'approved').limit(1).maybeSingle(); if (!membership) redirect('/workspace');
  const { data: rows } = await supabase.from('work_tasks').select('id,title,priority,status,due_at,labels').eq('organization_id', membership.organization_id).is('archived_at', null).order('created_at', { ascending: false });
  const now = new Date(); const tasks = ((rows ?? []) as Task[]).filter((task) => (!priority || task.priority === priority) && (!deadline || (deadline === 'overdue' ? !!task.due_at && new Date(task.due_at) < now && task.status !== 'done' : deadline === 'today' ? !!task.due_at && new Date(task.due_at).toDateString() === now.toDateString() : true)));
  return <main className="workspace-page"><header className="workspace-header"><Link className="brand" href="/"><span className="brand-mark">W</span><span>workhub</span></Link><div><strong>Tasks</strong><small>{tasks.length} matching tasks</small></div><Link className="back-link" href="/workspace">Workspace</Link></header><section className="workspace-content"><div className="workspace-intro"><p className="eyebrow"><span /> TASKS</p><h1>Plan work and deadlines</h1><p><Link href="/projects">Projects</Link> · <Link href="/calendar">Schedule</Link> · <Link href="/tasks/automation">Automation</Link> · <Link href="/tasks/templates">Templates</Link> · <Link href="/tasks/archive">Archive</Link></p></div><section className="workspace-panel"><form className="task-form"><label>Priority<select name="priority" defaultValue={priority}><option value="">All priorities</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label>Deadline<select name="deadline" defaultValue={deadline}><option value="">All deadlines</option><option value="today">Due today</option><option value="overdue">Overdue</option></select></label><button className="secondary">Apply filter</button></form></section><section className="workspace-panel"><h2>Add task</h2><form className="task-form" action={createTask}><input type="hidden" name="organizationId" value={membership.organization_id}/><input name="title" placeholder="What needs to be done?" required maxLength={200}/><input name="dueAt" type="date"/><select name="priority" defaultValue="medium"><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><button className="primary">Add task</button></form></section><section className="workspace-grid">{columns.map((column) => { const columnTasks = tasks.filter((task) => task.status === column.key); return <section className="workspace-panel" key={column.key}><div className="workspace-panel-title"><h2>{column.title}</h2><span>{columnTasks.length}</span></div>{columnTasks.length ? <div className="live-tasks">{columnTasks.map((task) => <form className="live-task" action={setTaskStatus} key={task.id}><input type="hidden" name="id" value={task.id}/><div><Link href={`/tasks/${task.id}`}><b>{task.title}</b></Link><small>{task.priority} priority · {task.due_at ? new Date(task.due_at).toLocaleDateString('ko-KR') : 'No deadline'}{task.labels?.length ? ` · ${task.labels.join(', ')}` : ''}</small></div><select name="status" defaultValue={task.status}><option value="todo">To do</option><option value="in_progress">In progress</option><option value="done">Done</option></select><button className="secondary">Move</button></form>)}</div> : <div className="empty-state">No tasks in this column.</div>}</section>; })}</section></section></main>;
}
