import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { assignMemberTeam, createDepartment, createTeam } from './actions';

type Department = { id: string; name: string }; type Team = { id: string; name: string; department_id: string | null }; type Member = { user_id: string; team_id: string | null; profiles: { full_name: string | null; email: string | null } | { full_name: string | null; email: string | null }[] | null };

export default async function StructurePage() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect('/login'); const { data: membership } = await supabase.from('organization_members').select('organization_id,role').eq('user_id', user.id).eq('status', 'approved').limit(1).maybeSingle();
  if (!membership || !['organization_admin', 'system_admin'].includes(membership.role)) return <main className="onboarding"><section className="onboarding-card"><h1>관리자 권한이 필요합니다</h1><Link className="primary" href="/workspace">내 공간</Link></section></main>;
  const [{ data: departmentRows }, { data: teamRows }, { data: memberRows }] = await Promise.all([supabase.from('departments').select('id,name').eq('organization_id', membership.organization_id).order('name'), supabase.from('teams').select('id,name,department_id').eq('organization_id', membership.organization_id).order('name'), supabase.from('organization_members').select('user_id,team_id,profiles(full_name,email)').eq('organization_id', membership.organization_id).eq('status', 'approved')]); const departments = (departmentRows ?? []) as Department[]; const teams = (teamRows ?? []) as Team[]; const members = (memberRows ?? []) as unknown as Member[];
  return <main className="workspace-page"><header className="workspace-header"><Link className="brand" href="/"><span className="brand-mark">W</span><span>workhub</span></Link><div><strong>조직 구조</strong><small>부서 {departments.length}개 · 팀 {teams.length}개</small></div><Link className="back-link" href="/manage/dashboard">관리자</Link></header><section className="workspace-content"><div className="workspace-intro"><p className="eyebrow"><span /> 관리자</p><h1>팀 구조를 구성하세요.</h1><p>부서와 팀을 만들고 승인된 구성원을 팀에 배정할 수 있습니다.</p></div><div className="workspace-grid"><section className="workspace-panel"><h2>부서</h2><form className="task-form" action={createDepartment}><input name="name" placeholder="새 부서 이름" required maxLength={100} /><button className="primary">부서 추가</button></form>{departments.length ? <div className="live-tasks">{departments.map((department) => <div className="live-task" key={department.id}><b>{department.name}</b></div>)}</div> : <div className="empty-state">아직 부서가 없습니다.</div>}</section><section className="workspace-panel"><h2>팀</h2><form className="task-form" action={createTeam}><input name="name" placeholder="새 팀 이름" required maxLength={100} /><select name="departmentId"><option value="">부서 없음</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select><button className="primary">팀 추가</button></form>{teams.length ? <div className="live-tasks">{teams.map((team) => <div className="live-task" key={team.id}><b>{team.name}</b><small>{departments.find((department) => department.id === team.department_id)?.name || '부서 없음'}</small></div>)}</div> : <div className="empty-state">아직 팀이 없습니다.</div>}</section></div><section className="workspace-panel"><div className="workspace-panel-title"><h2>구성원 배정</h2><span>{members.length}</span></div>{members.length ? <div className="live-tasks">{members.map((member) => { const profile = Array.isArray(member.profiles) ? member.profiles[0] : member.profiles; return <form className="live-task" action={assignMemberTeam} key={member.user_id}><input type="hidden" name="userId" value={member.user_id} /><div><b>{profile?.full_name || profile?.email || '이름 없는 사용자'}</b><small>{profile?.email || '이메일 없음'}</small></div><select name="teamId" defaultValue={member.team_id || ''}><option value="">팀 없음</option>{teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select><button className="secondary">배정</button></form>; })}</div> : <div className="empty-state">배정할 승인 구성원이 없습니다.</div>}</section></section></main>;
}
