import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';

type Task = { id: string; status: string; priority: string; assignee_id: string | null; due_at: string | null };
export default async function ReportsPage() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect('/login');
  const { data: membership } = await supabase.from('organization_members').select('organization_id').eq('user_id', user.id).eq('status', 'approved').limit(1).maybeSingle(); if (!membership) redirect('/workspace');
  const { data: taskRows } = await supabase.from('work_tasks').select('id,status,priority,assignee_id,due_at').eq('organization_id', membership.organization_id).is('archived_at', null); const { data: memberRows } = await supabase.from('organization_members').select('user_id,profiles(full_name,email)').eq('organization_id', membership.organization_id).eq('status', 'approved');
  const tasks = (taskRows ?? []) as Task[]; const overdue = tasks.filter((task) => task.due_at && new Date(task.due_at) < new Date() && task.status !== 'done');
  return <main className="workspace-page"><header className="workspace-header"><Link className="brand" href="/"><span className="brand-mark">W</span><span>workhub</span></Link><div><strong>Work report</strong><small>Team workload at a glance</small></div><Link className="back-link" href="/tasks">Tasks</Link></header><section className="workspace-content"><section className="workspace-grid">{['todo','in_progress','done'].map((status) => <article className="workspace-panel" key={status}><h2>{status.replace('_', ' ')}</h2><p>{tasks.filter((task) => task.status === status).length} tasks</p></article>)}<article className="workspace-panel"><h2>Overdue</h2><p>{overdue.length} open tasks</p></article></section><section className="workspace-panel"><h2>Workload by member</h2>{(memberRows ?? []).map((member: any) => { const name = member.profiles?.full_name || member.profiles?.email || 'Member'; const assigned = tasks.filter((task) => task.assignee_id === member.user_id); return <div className="live-task" key={member.user_id}><div><b>{name}</b><small>{assigned.filter((task) => task.status !== 'done').length} active · {assigned.filter((task) => task.status === 'done').length} done</small></div></div>; })}</section></section></main>;
}
