import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';

type Task = { id: string; status: string; priority: string; assignee_id: string | null; due_at: string | null };
const statusCards = [['할 일', 'todo'], ['진행 중', 'in_progress'], ['완료', 'done']] as const;

export default async function ReportsPage() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect('/login');
  const { data: membership } = await supabase.from('organization_members').select('organization_id').eq('user_id', user.id).eq('status', 'approved').limit(1).maybeSingle(); if (!membership) redirect('/workspace');
  const [{ data: taskRows }, { data: memberRows }] = await Promise.all([supabase.from('work_tasks').select('id,status,priority,assignee_id,due_at').eq('organization_id', membership.organization_id).is('archived_at', null), supabase.from('organization_members').select('user_id,profiles(full_name,email)').eq('organization_id', membership.organization_id).eq('status', 'approved')]);
  const tasks = (taskRows ?? []) as Task[]; const overdue = tasks.filter((task) => task.due_at && new Date(task.due_at) < new Date() && task.status !== 'done');
  return <main className="workspace-page"><header className="workspace-header"><Link className="brand" href="/"><span className="brand-mark">W</span><span>workhub</span></Link><div><strong>업무 보고서</strong><small>팀 업무 현황 요약</small></div><Link className="back-link" href="/tasks">업무</Link></header><section className="workspace-content"><div className="workspace-intro"><p className="eyebrow"><span /> 보고서</p><h1>업무 현황을 확인하세요.</h1><p>현재 워크스페이스의 활성 업무를 기준으로 집계합니다.</p></div><section className="workspace-grid">{statusCards.map(([label, status]) => <article className="workspace-panel" key={status}><h2>{label}</h2><p>{tasks.filter((task) => task.status === status).length}개</p></article>)}<article className="workspace-panel"><h2>기한 초과</h2><p>{overdue.length}개 미완료</p></article></section><section className="workspace-panel"><div className="workspace-panel-title"><h2>구성원별 업무량</h2><span>{memberRows?.length ?? 0}</span></div>{memberRows?.length ? <div className="live-tasks">{memberRows.map((member: any) => { const profile = Array.isArray(member.profiles) ? member.profiles[0] : member.profiles; const name = profile?.full_name || profile?.email || '구성원'; const assigned = tasks.filter((task) => task.assignee_id === member.user_id); return <div className="live-task" key={member.user_id}><div><b>{name}</b><small>진행 {assigned.filter((task) => task.status !== 'done').length}개 · 완료 {assigned.filter((task) => task.status === 'done').length}개</small></div></div>; })}</div> : <div className="empty-state">승인된 구성원이 없습니다.</div>}</section>{!tasks.length && <section className="workspace-panel empty-state">활성 업무가 없습니다. 업무를 추가하면 이 보고서에 현황이 표시됩니다.</section>}</section></main>;
}
