import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';

export default async function MyActivityPage() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect('/login');
  const [{ data: posts }, { data: comments }, { data: tasks }, { data: notifications }] = await Promise.all([supabase.from('posts').select('id,title,status,created_at').eq('author_id', user.id).order('created_at', { ascending: false }).limit(10), supabase.from('comments').select('id,body,created_at').eq('author_id', user.id).order('created_at', { ascending: false }).limit(10), supabase.from('work_tasks').select('id,title,status,created_at').or(`creator_id.eq.${user.id},assignee_id.eq.${user.id}`).order('created_at', { ascending: false }).limit(10), supabase.from('notifications').select('id,title,created_at,read_at').eq('user_id', user.id).order('created_at', { ascending: false }).limit(10)]);
  const unread = (notifications ?? []).filter((item) => !item.read_at).length;
  return <main className="workspace-page"><header className="workspace-header"><Link className="brand" href="/"><span className="brand-mark">W</span><span>workhub</span></Link><div><strong>내 활동</strong><small>최근 작업과 업데이트</small></div><Link className="back-link" href="/me">마이페이지</Link></header><section className="workspace-content"><div className="workspace-intro"><p className="eyebrow"><span /> 활동</p><h1>최근 활동</h1><p>작성한 글, 참여한 대화, 배정된 업무를 한눈에 확인하세요.</p></div><section className="workspace-grid">{[['게시글', posts?.length ?? 0, '/posts'], ['댓글', comments?.length ?? 0, '/me/activity'], ['업무', tasks?.length ?? 0, '/tasks'], ['읽지 않은 알림', unread, '/notifications']].map(([label, count, href]) => <Link className="workspace-panel" href={href as string} key={label as string}><h2>{label}</h2><p>최근 {count}개</p></Link>)}</section><section className="workspace-grid"><section className="workspace-panel"><div className="workspace-panel-title"><h2>최근 게시글</h2><Link href="/posts">전체 보기</Link></div>{posts?.length ? <div className="live-tasks">{posts.map((post) => <Link className="live-task" key={post.id} href={`/posts/${post.id}`}><div><b>{post.title}</b><small>{post.status} · {new Date(post.created_at).toLocaleDateString('ko-KR')}</small></div></Link>)}</div> : <div className="empty-state">작성한 게시글이 없습니다.</div>}</section><section className="workspace-panel"><div className="workspace-panel-title"><h2>최근 업무</h2><Link href="/tasks">전체 보기</Link></div>{tasks?.length ? <div className="live-tasks">{tasks.map((task) => <Link className="live-task" key={task.id} href={`/tasks/${task.id}`}><div><b>{task.title}</b><small>{task.status} · {new Date(task.created_at).toLocaleDateString('ko-KR')}</small></div></Link>)}</div> : <div className="empty-state">배정된 업무가 없습니다.</div>}</section></section></section></main>;
}
