import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { addTaskComment, archiveTask, updateTaskDetails } from '../actions';
export default async function TaskDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect('/login');
  const { data: task } = await supabase.from('work_tasks').select('id,organization_id,title,description,priority,status,start_at,due_at,project_id,labels,recurrence,archived_at').eq('id', id).maybeSingle(); if (!task || task.archived_at) notFound();
  const { data: projects } = await supabase.from('projects').select('id,name').eq('organization_id', task.organization_id).neq('status','archived').order('name'); const { data: comments } = await supabase.from('task_comments').select('id,body,created_at,profiles(full_name,email)').eq('task_id', id).order('created_at');
  return <main className="workspace-page"><header className="workspace-header"><Link className="brand" href="/"><span className="brand-mark">W</span><span>workhub</span></Link><div><strong>Task details</strong><small>Plan, discuss and track work</small></div><Link className="back-link" href="/tasks">Tasks</Link></header><section className="workspace-content"><section className="workspace-panel"><form className="task-form" action={updateTaskDetails}><input type="hidden" name="id" value={task.id}/><input name="title" defaultValue={task.title} required maxLength={200}/><textarea name="description" defaultValue={task.description ?? ''} placeholder="Description" maxLength={5000}/><label>Project<select name="projectId" defaultValue={task.project_id ?? ''}><option value="">No project</option>{(projects ?? []).map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>Status<select name="status" defaultValue={task.status}><option value="todo">To do</option><option value="in_progress">In progress</option><option value="done">Done</option></select></label><label>Priority<select name="priority" defaultValue={task.priority}><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label>Start<input type="date" name="startAt" defaultValue={task.start_at ?? ''}/></label><label>Due<input type="date" name="dueAt" defaultValue={task.due_at ? String(task.due_at).slice(0,10) : ''}/></label><label>Labels (comma separated)<input name="labels" defaultValue={(task.labels ?? []).join(', ')}/></label><label>Repeat<select name="recurrence" defaultValue={task.recurrence ?? ''}><option value="">Does not repeat</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><button className="primary">Save task</button></form><form action={archiveTask}><input type="hidden" name="id" value={task.id}/><button className="secondary">Archive task</button></form></section><section className="workspace-panel"><h2>Comments</h2><form className="task-form" action={addTaskComment}><input type="hidden" name="taskId" value={task.id}/><textarea name="body" placeholder="Write an update or question" required maxLength={3000}/><button className="primary">Add comment</button></form>{(comments ?? []).map((comment: any) => <article className="live-task" key={comment.id}><div><b>{comment.profiles?.full_name || comment.profiles?.email || 'Member'}</b><small>{new Date(comment.created_at).toLocaleString('ko-KR')}</small><p>{comment.body}</p></div></article>)}</section></section></main>;
}
