import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import './workspace/workspace.css';

export default async function Home() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser();
  if (!user) return <main className="onboarding"><section className="onboarding-card"><Link className="brand" href="/"><span className="brand-mark">W</span><span>workhub</span></Link><p className="eyebrow"><span /> WORKHUB</p><h1>Work together with clarity.</h1><p>Organize your team’s work, knowledge, documents, and updates in one place.</p><Link className="primary" href="/login">Log in to WorkHub</Link><Link className="secondary" href="/posts">Browse public posts</Link></section></main>;
  const { data: membership } = await supabase.from('organization_members').select('organization_id').eq('user_id', user.id).eq('status', 'approved').limit(1).maybeSingle();
  if (!membership) return <main className="onboarding"><section className="onboarding-card"><h1>Welcome to WorkHub</h1><p>Create or join a workspace to begin.</p><Link className="primary" href="/workspace">Open workspace</Link></section></main>;
  const org = membership.organization_id; const today = new Date().toISOString(); const [{ data: tasks }, { data: posts }, { data: notices }, { data: alerts }] = await Promise.all([supabase.from('work_tasks').select('id,title,status,due_at,priority').eq('organization_id', org).is('archived_at', null).or(`assignee_id.eq.${user.id},creator_id.eq.${user.id}`).order('due_at').limit(8), supabase.from('posts').select('id,title,created_at').eq('organization_id',org).eq('status','published').order('created_at',{ascending:false}).limit(5), supabase.from('notices').select('id,title,pinned,created_at').eq('organization_id',org).eq('status','published').order('pinned',{ascending:false}).order('created_at',{ascending:false}).limit(3), supabase.from('notifications').select('id').eq('user_id',user.id).is('read_at',null)]);
  const active=(tasks??[]).filter(t=>t.status!=='done').length; const overdue=(tasks??[]).filter(t=>t.due_at&&new Date(t.due_at)<new Date()&&t.status!=='done').length;
  return <main className="workspace-page"><header className="workspace-header"><Link className="brand" href="/"><span className="brand-mark">W</span><span>workhub</span></Link><div><strong>Overview</strong><small>{user.email}</small></div><div className="hero-actions"><Link className="secondary" href="/notifications">{alerts?.length??0} alerts</Link><Link className="primary" href="/workspace">Workspace</Link></div></header><section className="workspace-content"><div className="workspace-intro"><p className="eyebrow"><span /> DASHBOARD</p><h1>Your workspace at a glance</h1><p>Keep track of what needs your attention today.</p></div><section className="workspace-grid"><article className="workspace-panel"><h2>Active tasks</h2><p>{active}</p><Link href="/tasks">View tasks</Link></article><article className="workspace-panel"><h2>Overdue tasks</h2><p>{overdue}</p><Link href="/calendar">Open schedule</Link></article><article className="workspace-panel"><h2>Unread alerts</h2><p>{alerts?.length??0}</p><Link href="/notifications">Open notifications</Link></article></section><section className="workspace-grid"><section className="workspace-panel"><div className="workspace-panel-title"><h2>My tasks</h2><Link href="/tasks">All tasks</Link></div>{(tasks??[]).map(t=><Link className="live-task" href={`/tasks/${t.id}`} key={t.id}><div><b>{t.title}</b><small>{t.status} · {t.priority} · {t.due_at?new Date(t.due_at).toLocaleDateString('ko-KR'):'No deadline'}</small></div></Link>)}</section><section className="workspace-panel"><div className="workspace-panel-title"><h2>Latest posts</h2><Link href="/posts">All posts</Link></div>{(posts??[]).map(p=><Link className="live-task" href={`/posts/${p.id}`} key={p.id}><div><b>{p.title}</b><small>{new Date(p.created_at).toLocaleDateString('ko-KR')}</small></div></Link>)}</section><section className="workspace-panel"><div className="workspace-panel-title"><h2>Notices</h2><Link href="/notices">All notices</Link></div>{(notices??[]).map(n=><Link className="live-task" href="/notices" key={n.id}><div><b>{n.pinned?'Pinned · ':''}{n.title}</b><small>{new Date(n.created_at).toLocaleDateString('ko-KR')}</small></div></Link>)}</section></section></section></main>;
}
