import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { createNotice, deleteNotice, updateNoticeState } from './actions';

type Notice = { id: string; title: string; body: string; status: string; pinned: boolean; created_at: string };
export default async function ManageNoticesPage() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect('/login');
  const { data: membership } = await supabase.from('organization_members').select('organization_id, role').eq('user_id', user.id).eq('status', 'approved').limit(1).maybeSingle();
  if (!membership || !['organization_admin', 'system_admin'].includes(membership.role)) return <main className="onboarding"><section className="onboarding-card"><h1>Administrator access required</h1><Link className="primary" href="/workspace">Back to workspace</Link></section></main>;
  const { data: rows } = await supabase.from('notices').select('id, title, body, status, pinned, created_at').eq('organization_id', membership.organization_id).order('pinned', { ascending: false }).order('created_at', { ascending: false });
  const notices = (rows ?? []) as Notice[];
  return <main className="workspace-page"><header className="workspace-header"><Link className="brand" href="/"><span className="brand-mark">W</span><span>workhub</span></Link><div><strong>Notice management</strong><small>Drafts and publishing</small></div><Link className="back-link" href="/workspace">Workspace</Link></header><section className="workspace-content"><div className="workspace-grid"><section className="workspace-panel"><h2>Create notice</h2><form className="task-form" action={createNotice}><label htmlFor="title">Title</label><input id="title" name="title" required maxLength={200} /><label htmlFor="body">Content</label><textarea id="body" name="body" rows={8} /><label><input type="checkbox" name="publish" /> Publish now</label><label><input type="checkbox" name="pinned" /> Pin notice</label><button className="primary">Save notice</button></form></section><section className="workspace-panel"><div className="workspace-panel-title"><h2>Notices</h2><span>{notices.length}</span></div><div className="live-tasks">{notices.map((notice) => <div className="live-task" key={notice.id}><div><b>{notice.pinned ? 'PINNED · ' : ''}{notice.title}</b><small>{notice.status} · {notice.body.slice(0, 100)}</small></div><div className="hero-actions"><form action={updateNoticeState}><input type="hidden" name="id" value={notice.id} /><input type="hidden" name="status" value={notice.status === 'published' ? 'draft' : 'published'} /><input type="hidden" name="pinned" value={String(notice.pinned)} /><button className="secondary">{notice.status === 'published' ? 'Unpublish' : 'Publish'}</button></form><form action={updateNoticeState}><input type="hidden" name="id" value={notice.id} /><input type="hidden" name="status" value={notice.status} /><input type="hidden" name="pinned" value={String(!notice.pinned)} /><button className="secondary">{notice.pinned ? 'Unpin' : 'Pin'}</button></form><form action={deleteNotice}><input type="hidden" name="id" value={notice.id} /><button className="secondary">Delete</button></form></div></div>)}</div></section></div></section></main>;
}
