import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { createNotice, deleteNotice, updateNoticeState } from './actions';

type Notice = { id: string; title: string; body: string; status: string; pinned: boolean; created_at: string };

export default async function ManageNoticesPage() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect('/login');
  const { data: membership } = await supabase.from('organization_members').select('organization_id,role').eq('user_id', user.id).eq('status', 'approved').limit(1).maybeSingle();
  if (!membership || !['organization_admin', 'system_admin'].includes(membership.role)) return <main className="onboarding"><section className="onboarding-card"><h1>관리자 권한이 필요합니다</h1><Link className="primary" href="/workspace">내 공간</Link></section></main>;
  const { data: rows } = await supabase.from('notices').select('id,title,body,status,pinned,created_at').eq('organization_id', membership.organization_id).order('pinned', { ascending: false }).order('created_at', { ascending: false }); const notices = (rows ?? []) as Notice[];
  return <main className="workspace-page"><header className="workspace-header"><Link className="brand" href="/"><span className="brand-mark">W</span><span>workhub</span></Link><div><strong>공지 관리</strong><small>공지 {notices.length}개</small></div><Link className="back-link" href="/manage/dashboard">관리자</Link></header><section className="workspace-content"><div className="workspace-intro"><p className="eyebrow"><span /> 관리자</p><h1>공지를 작성하고 게시하세요.</h1><p>공식 업데이트를 게시하고 중요한 공지는 상단에 고정할 수 있습니다.</p></div><div className="workspace-grid"><section className="workspace-panel"><h2>공지 작성</h2><form className="task-form" action={createNotice}><label>제목<input name="title" required maxLength={200} /></label><label>내용<textarea name="body" rows={8} /></label><label><input type="checkbox" name="publish" /> 바로 게시</label><label><input type="checkbox" name="pinned" /> 상단 고정</label><button className="primary">공지 저장</button></form></section><section className="workspace-panel"><div className="workspace-panel-title"><h2>공지 목록</h2><span>{notices.length}</span></div>{notices.length ? <div className="live-tasks">{notices.map((notice) => <div className="live-task" key={notice.id}><div><b>{notice.pinned ? '고정 · ' : ''}{notice.title}</b><small>{notice.status === 'published' ? '게시됨' : '초안'} · {notice.body.slice(0, 100) || '내용 없음'}</small></div><div className="hero-actions"><form action={updateNoticeState}><input type="hidden" name="id" value={notice.id} /><input type="hidden" name="status" value={notice.status === 'published' ? 'draft' : 'published'} /><input type="hidden" name="pinned" value={String(notice.pinned)} /><button className="secondary">{notice.status === 'published' ? '게시 취소' : '게시'}</button></form><form action={updateNoticeState}><input type="hidden" name="id" value={notice.id} /><input type="hidden" name="status" value={notice.status} /><input type="hidden" name="pinned" value={String(!notice.pinned)} /><button className="secondary">{notice.pinned ? '고정 해제' : '고정'}</button></form><form action={deleteNotice}><input type="hidden" name="id" value={notice.id} /><button className="secondary">삭제</button></form></div></div>)}</div> : <div className="empty-state">아직 공지가 없습니다. 첫 공지를 작성해 보세요.</div>}</section></div></section></main>;
}
