'use server';
import { decryptApiKey } from '@/lib/ai/crypto';
import { createClient } from '@/lib/supabase/server';
type AiResult = { ok: boolean; text: string };
type Settings = { provider: string; encrypted_api_key: string; model: string | null; base_url: string | null };
function errorMessage(data: unknown, fallback: string) { if (!data || typeof data !== 'object') return fallback; const value = data as { error?: { message?: string } | string; message?: string }; return typeof value.error === 'string' ? value.error : value.error?.message || value.message || fallback; }
async function compatibleRequest(settings: Settings, prompt: string, key: string): Promise<AiResult> { const defaults: Record<string, string> = { openrouter: 'https://openrouter.ai/api/v1', deepseek: 'https://api.deepseek.com/v1', groq: 'https://api.groq.com/openai/v1' }; const base = (settings.base_url || defaults[settings.provider] || '').replace(/\/$/, ''); if (!base) return { ok: false, text: 'AI 설정에서 HTTPS Base URL을 입력해 주세요.' }; const response = await fetch(`${base}/chat/completions`, { method: 'POST', headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: settings.model || 'default', messages: [{ role: 'user', content: prompt }], temperature: 0.3 }), cache: 'no-store' }); const data = await response.json().catch(() => null) as { choices?: Array<{ message?: { content?: string } }> } | null; return response.ok ? { ok: true, text: data?.choices?.[0]?.message?.content?.trim() || '응답 텍스트가 없습니다.' } : { ok: false, text: errorMessage(data, 'AI 요청에 실패했습니다.') }; }
async function callAi(prompt: string): Promise<AiResult> { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return { ok: false, text: '먼저 로그인해 주세요.' }; const { data: settings } = await supabase.from('user_ai_settings').select('provider,encrypted_api_key,model,base_url').eq('user_id', user.id).maybeSingle(); if (!settings) return { ok: false, text: 'AI 설정에서 API 키를 먼저 저장해 주세요.' }; try { const key = decryptApiKey(settings.encrypted_api_key); if (settings.provider === 'openai') { const response = await fetch(`${(settings.base_url || 'https://api.openai.com/v1').replace(/\/$/, '')}/responses`, { method: 'POST', headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: settings.model || 'gpt-4.1-mini', input: prompt }), cache: 'no-store' }); const data = await response.json().catch(() => null) as { output_text?: string } | null; return response.ok ? { ok: true, text: data?.output_text?.trim() || '응답 텍스트가 없습니다.' } : { ok: false, text: errorMessage(data, 'OpenAI 요청에 실패했습니다.') }; } if (settings.provider === 'anthropic') { const response = await fetch(`${(settings.base_url || 'https://api.anthropic.com/v1').replace(/\/$/, '')}/messages`, { method: 'POST', headers: { 'x-api-key': key, 'anthropic-version': '2023-06-01', 'Content-Type': 'application/json' }, body: JSON.stringify({ model: settings.model || 'claude-3-5-haiku-latest', max_tokens: 1000, messages: [{ role: 'user', content: prompt }] }), cache: 'no-store' }); const data = await response.json().catch(() => null) as { content?: Array<{ text?: string }> } | null; return response.ok ? { ok: true, text: data?.content?.map((item) => item.text || '').join('\n').trim() || '응답 텍스트가 없습니다.' } : { ok: false, text: errorMessage(data, 'Anthropic 요청에 실패했습니다.') }; } if (settings.provider === 'gemini') { const model = settings.model || 'gemini-2.0-flash'; const base = (settings.base_url || 'https://generativelanguage.googleapis.com/v1beta').replace(/\/$/, ''); const response = await fetch(`${base}/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] }), cache: 'no-store' }); const data = await response.json().catch(() => null) as { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }> } | null; return response.ok ? { ok: true, text: data?.candidates?.[0]?.content?.parts?.map((item) => item.text || '').join('\n').trim() || '응답 텍스트가 없습니다.' } : { ok: false, text: errorMessage(data, 'Gemini 요청에 실패했습니다.') }; } return compatibleRequest(settings, prompt, key); } catch { return { ok: false, text: 'AI 제공자에 연결하지 못했습니다. API 키, 모델, Base URL을 확인해 주세요.' }; } }
export async function testAiConnection() { const result = await callAi('WorkHub 연결 테스트입니다. 정확히 "연결 성공"이라고만 답하세요.'); if (result.ok) { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (user) await supabase.from('user_ai_settings').update({ last_tested_at: new Date().toISOString() }).eq('user_id', user.id); } return result; }
export async function summarizeText(formData: FormData) { const content = String(formData.get('content') ?? '').trim(); return content ? callAi(`다음 텍스트를 한국어 핵심 3개 항목으로 요약하세요. 원문에 없는 정보는 추가하지 마세요.\n\n${content.slice(0, 12000)}`) : { ok: false, text: '요약할 텍스트를 입력해 주세요.' }; }
export async function suggestTitles(formData: FormData) { const content = String(formData.get('content') ?? '').trim(); return content ? callAi(`다음 게시글에 어울리는 간결한 한국어 제목 5개를 번호 목록으로 제안하세요.\n\n${content.slice(0, 12000)}`) : { ok: false, text: '게시글 초안을 입력해 주세요.' }; }
export async function improvePostDraft(formData: FormData) { const content = String(formData.get('content') ?? '').trim(), mode = String(formData.get('mode') ?? 'tags'); if (!content) return { ok: false, text: '게시글 초안을 입력해 주세요.' }; const instructions: Record<string, string> = { tags: '핵심 태그 5개를 #태그 형식으로만 제안하세요.', proofread: '맞춤법과 문장 흐름을 교정한 완성본만 반환하세요. 사실과 의미는 바꾸지 마세요.', rewrite: '더 명확하고 읽기 쉬운 한국어 문장으로 다듬은 완성본만 반환하세요. Markdown 구조는 유지하세요.', category: '가장 알맞은 카테고리 이름 1개와 그 이유를 한 줄로 제안하세요.', seo: 'SEO 제목(60자 이내), 메타 설명(155자 이내), 핵심 키워드 5개를 한국어로 제안하세요.', meta: '검색 결과에 사용할 매력적인 메타 설명을 155자 이내로 하나 작성하세요.', alt: '본문 속 이미지에 쓸 수 있는 접근성 좋은 대체 텍스트 3개를 제안하세요.' }; return instructions[mode] ? callAi(`다음 게시글을 분석하세요. ${instructions[mode]}\n\n${content.slice(0, 12000)}`) : { ok: false, text: '지원하지 않는 AI 작업입니다.' }; }
