import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import styles from './dashboard.module.css';

export default async function AdminDashboardPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect('/login');
  const { data: primaryOrganization } = await supabase.from('organizations').select('id').order('created_at', { ascending: true }).order('id').limit(1).maybeSingle();
  const { data: membership } = primaryOrganization ? await supabase.from('organization_members').select('organization_id,role').eq('organization_id', primaryOrganization.id).eq('user_id', user.id).eq('status', 'approved').maybeSingle() : { data: null };
  if (!membership || !['organization_admin', 'system_admin'].includes(membership.role)) return <main className="onboarding"><section className="onboarding-card"><h1>관리자 권한이 필요합니다.</h1><p>승인된 조직 관리자와 최고관리자만 이용할 수 있습니다.</p><Link className="primary" href="/">홈으로</Link></section></main>;
  const organizationId = membership.organization_id;
  const [{ count: accounts }, { count: pending }, { count: posts }, { count: comments }, { count: documents }, { count: tasks }, { data: logs }] = await Promise.all([
    supabase.from('profiles').select('*', { count: 'exact', head: true }), supabase.from('organization_members').select('*', { count: 'exact', head: true }).eq('organization_id', organizationId).eq('status', 'pending'), supabase.from('posts').select('*', { count: 'exact', head: true }).eq('organization_id', organizationId).eq('status', 'published'), supabase.from('comments').select('id,posts!inner(organization_id)', { count: 'exact', head: true }).eq('posts.organization_id', organizationId), supabase.from('documents').select('*', { count: 'exact', head: true }).eq('organization_id', organizationId), supabase.from('work_tasks').select('*', { count: 'exact', head: true }).eq('organization_id', organizationId), supabase.from('audit_logs').select('id,action,created_at').eq('organization_id', organizationId).order('created_at', { ascending: false }).limit(8),
  ]);
  const cards: [string, number | null, string, string][] = [['전체 구성원', accounts, '사이트에 로그인한 전체 계정', '/manage/members'], ['승인 대기', pending, '관리자 승인을 기다리는 계정', '/manage/members/pending'], ['공개 게시글', posts, '현재 공개된 게시글', '/manage/posts'], ['댓글', comments, '게시글에 작성된 댓글', '/manage/comments'], ['문서', documents, '공유된 워크스페이스 문서', '/documents'], ['업무', tasks, '등록된 업무 항목', '/tasks']];
  const sections: [string, string, string][] = [['공지 관리', '공지 작성과 게시 상태 관리', '/manage/notices'], ['광고 관리', '광고 캠페인과 배치 관리', '/manage/ads'], ['분석', '방문·게시글·광고 활동 확인', '/manage/analytics'], ['감사 로그', '관리자와 시스템 작업 확인', '/manage/audit'], ['배너 관리', '안내 배너 작성과 게시', '/manage/banners'], ['댓글 관리', '댓글 검토 및 삭제', '/manage/comments'], ['보호 링크', '권한이 필요한 링크 관리', '/manage/protected-links'], ['사이트 설정', '홈과 사이트 옵션 관리', '/manage/site'], ['조직 구조', '부서·팀 구조 관리', '/manage/structure'], ['카테고리·태그', '게시글 분류 관리', '/manage/taxonomy']];
  return <main className="workspace-page"><header className="workspace-header"><Link className="brand" href="/"><span className="brand-mark">W</span><span>workhub</span></Link><div><strong>관리자 대시보드</strong><small>워크스페이스 운영 현황과 관리 도구</small></div><Link className="back-link" href="/">홈</Link></header><section className={`workspace-content ${styles.dashboard}`}><div className={styles.hero}><div><p className="eyebrow"><span /> ADMINISTRATION</p><h1>관리자 대시보드</h1><p>구성원, 승인 요청, 콘텐츠와 운영 현황을 관리합니다.</p></div><div className={styles.heroActions}><span className={styles.role}>{membership.role === 'system_admin' ? '최고관리자' : '조직 관리자'}</span><Link className="primary" href="/manage/members">구성원 관리</Link></div></div><section className={styles.memberSummary}><Link href="/manage/members"><b>전체 구성원</b><strong>{accounts ?? 0}명</strong><small>로그인 계정 전체 보기</small></Link><Link href="/manage/members/pending"><b>승인 대기</b><strong>{pending ?? 0}명</strong><small>승인 요청 바로 처리</small></Link></section><section className={styles.cards}>{cards.map(([label, value, description, href]) => <Link className={styles.card} href={href} key={label}><span>{label}</span><strong>{value ?? 0}</strong><small>{description}</small><i>열기 →</i></Link>)}</section><section className={styles.columns}><section className="workspace-panel"><div className="workspace-panel-title"><div><h2>빠른 관리</h2><p className={styles.panelCopy}>자주 사용하는 관리 도구입니다.</p></div></div><div className={styles.quickLinks}>{sections.map(([label, description, href]) => <Link href={href} key={label}><b>{label}</b><small>{description}</small><span>→</span></Link>)}</div></section><section className="workspace-panel"><div className="workspace-panel-title"><div><h2>최근 운영 기록</h2><p className={styles.panelCopy}>관리자와 시스템 변경 기록입니다.</p></div><Link href="/manage/audit">전체 보기</Link></div>{logs?.length ? <div className="live-tasks">{logs.map((log) => <div className="live-task" key={log.id}><div><b>{log.action}</b><small>{new Date(log.created_at).toLocaleString('ko-KR')}</small></div></div>)}</div> : <div className="empty-state">아직 기록된 운영 활동이 없습니다.</div>}</section></section></section></main>;
}
