import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { createAd, setAdStatus } from './actions';

type Ad = { id: string; title: string; target_url: string; placement: string; status: string; click_count: number };
const label = (value: string, labels: Record<string, string>) => labels[value] ?? value;

export default async function AdsPage() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect('/login');
  const { data: membership } = await supabase.from('organization_members').select('organization_id,role').eq('user_id', user.id).eq('status', 'approved').limit(1).maybeSingle();
  if (!membership || !['organization_admin', 'system_admin'].includes(membership.role)) return <main className="onboarding"><section className="onboarding-card"><h1>관리자 권한이 필요합니다</h1><Link className="primary" href="/workspace">내 공간</Link></section></main>;
  const { data: rows } = await supabase.from('advertisements').select('id,title,target_url,placement,status,click_count').eq('organization_id', membership.organization_id).order('created_at', { ascending: false }); const ads = (rows ?? []) as Ad[];
  return <main className="workspace-page"><header className="workspace-header"><Link className="brand" href="/"><span className="brand-mark">W</span><span>workhub</span></Link><div><strong>광고 관리</strong><small>캠페인 {ads.length}개</small></div><Link className="back-link" href="/manage/dashboard">관리자</Link></header><section className="workspace-content"><div className="workspace-intro"><p className="eyebrow"><span /> 관리자</p><h1>워크스페이스 광고를 관리하세요.</h1><p>광고를 만들고 노출 위치와 게시 상태를 설정할 수 있습니다.</p></div><section className="workspace-grid"><section className="workspace-panel"><h2>광고 만들기</h2><form className="task-form" action={createAd}><input name="title" placeholder="광고 제목" required /><input name="targetUrl" type="url" placeholder="https://target.example" required /><input name="imageUrl" type="url" placeholder="이미지 URL (선택)" /><select name="placement"><option value="header">상단</option><option value="sidebar">사이드바</option><option value="footer">하단</option><option value="post">게시글</option></select><label><input type="checkbox" name="publish" /> 바로 게시</label><button className="primary">광고 저장</button></form></section><section className="workspace-panel"><div className="workspace-panel-title"><h2>캠페인</h2><span>{ads.length}</span></div>{ads.length ? <div className="live-tasks">{ads.map((ad) => <div className="live-task" key={ad.id}><div><b>{ad.title}</b><small>{label(ad.placement, { header: '상단', sidebar: '사이드바', footer: '하단', post: '게시글' })} · {label(ad.status, { draft: '초안', published: '게시됨', paused: '일시 중지', archived: '보관됨' })} · 클릭 {ad.click_count}회</small></div><form action={setAdStatus}><input type="hidden" name="id" value={ad.id} /><select name="status" defaultValue={ad.status}><option value="draft">초안</option><option value="published">게시</option><option value="paused">일시 중지</option><option value="archived">보관</option></select><button className="secondary">저장</button></form></div>)}</div> : <div className="empty-state">아직 캠페인이 없습니다. 첫 광고를 만들어 보세요.</div>}</section></section></section></main>;
}
