import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { createBanner, deleteBanner, setBannerStatus } from './actions';

type Banner = { id: string; title: string; message: string; link_url: string | null; placement: string; status: string };
const placement = (value: string) => ({ top: '상단', sidebar: '사이드바', footer: '하단' }[value] ?? value);
const status = (value: string) => ({ draft: '초안', published: '게시됨', archived: '보관됨' }[value] ?? value);

export default async function BannersPage() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect('/login'); const { data: membership } = await supabase.from('organization_members').select('organization_id,role').eq('user_id', user.id).eq('status', 'approved').limit(1).maybeSingle();
  if (!membership || !['organization_admin', 'system_admin'].includes(membership.role)) return <main className="onboarding"><section className="onboarding-card"><h1>관리자 권한이 필요합니다</h1><Link className="primary" href="/workspace">내 공간</Link></section></main>;
  const { data: rows } = await supabase.from('banners').select('id,title,message,link_url,placement,status').eq('organization_id', membership.organization_id).order('created_at', { ascending: false }); const banners = (rows ?? []) as Banner[];
  return <main className="workspace-page"><header className="workspace-header"><Link className="brand" href="/"><span className="brand-mark">W</span><span>workhub</span></Link><div><strong>배너 관리</strong><small>배너 {banners.length}개</small></div><Link className="back-link" href="/manage/dashboard">관리자</Link></header><section className="workspace-content"><div className="workspace-intro"><p className="eyebrow"><span /> 관리자</p><h1>워크스페이스 배너를 관리하세요.</h1><p>짧은 안내 문구를 원하는 위치에 게시할 수 있습니다.</p></div><section className="workspace-grid"><section className="workspace-panel"><h2>배너 만들기</h2><form className="task-form" action={createBanner}><input name="title" placeholder="배너 제목" required maxLength={120} /><textarea name="message" placeholder="짧은 안내 문구" maxLength={500} /><input name="linkUrl" placeholder="https://example.com (선택)" /><select name="placement" defaultValue="top"><option value="top">상단</option><option value="sidebar">사이드바</option><option value="footer">하단</option></select><label><input type="checkbox" name="publish" /> 바로 게시</label><button className="primary">배너 저장</button></form></section><section className="workspace-panel"><div className="workspace-panel-title"><h2>배너 목록</h2><span>{banners.length}</span></div>{banners.length ? <div className="live-tasks">{banners.map((banner) => <div className="live-task" key={banner.id}><div><b>{banner.title}</b><small>{status(banner.status)} · {placement(banner.placement)} · {banner.message}</small></div><div className="hero-actions"><form action={setBannerStatus}><input type="hidden" name="id" value={banner.id} /><select name="status" defaultValue={banner.status}><option value="draft">초안</option><option value="published">게시</option><option value="archived">보관</option></select><button className="secondary">저장</button></form><form action={deleteBanner}><input type="hidden" name="id" value={banner.id} /><button className="secondary">삭제</button></form></div></div>)}</div> : <div className="empty-state">아직 배너가 없습니다. 첫 워크스페이스 안내를 작성해 보세요.</div>}</section></section></section></main>;
}
