create table public.work_tasks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, creator_id uuid not null references public.profiles(id), assignee_id uuid references public.profiles(id), title text not null check (char_length(title) between 1 and 200), description text not null default '', priority text not null default 'medium' check (priority in ('low', 'medium', 'high')), status text not null default 'todo' check (status in ('todo', 'in_progress', 'done')), due_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.work_tasks enable row level security;
create or replace function public.add_organization_creator() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.organization_members (organization_id, user_id, role) values (new.id, new.created_by, 'organization_admin'); return new; end; $$;
create trigger on_organization_created after insert on public.organizations for each row execute procedure public.add_organization_creator();
create policy "users create organizations" on public.organizations for insert to authenticated with check (created_by = auth.uid());
create policy "members read tasks" on public.work_tasks for select to authenticated using (exists (select 1 from public.organization_members m where m.organization_id = work_tasks.organization_id and m.user_id = auth.uid()));
create policy "members create tasks" on public.work_tasks for insert to authenticated with check (creator_id = auth.uid() and exists (select 1 from public.organization_members m where m.organization_id = work_tasks.organization_id and m.user_id = auth.uid()));
create policy "task creators update tasks" on public.work_tasks for update to authenticated using (creator_id = auth.uid() or assignee_id = auth.uid()) with check (creator_id = auth.uid() or assignee_id = auth.uid());
create policy "task creators delete tasks" on public.work_tasks for delete to authenticated using (creator_id = auth.uid());
