alter table public.projects add column if not exists progress_note text not null default '';
alter table public.projects add column if not exists completed_at timestamptz;
create table if not exists public.project_milestones (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, creator_id uuid not null references public.profiles(id), title text not null check(char_length(title) between 1 and 200), due_at date, status text not null default 'planned' check(status in ('planned','in_progress','completed')), completed_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.project_updates (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, author_id uuid not null references public.profiles(id), body text not null check(char_length(body) between 1 and 3000), created_at timestamptz not null default now());
alter table public.project_milestones enable row level security; alter table public.project_updates enable row level security;
create policy "members read milestones" on public.project_milestones for select to authenticated using(exists(select 1 from public.projects p where p.id=project_id and public.is_organization_member(p.organization_id)));
create policy "creators manage milestones" on public.project_milestones for all to authenticated using(creator_id=auth.uid()) with check(creator_id=auth.uid());
create policy "members read project updates" on public.project_updates for select to authenticated using(exists(select 1 from public.projects p where p.id=project_id and public.is_organization_member(p.organization_id)));
create policy "members create project updates" on public.project_updates for insert to authenticated with check(author_id=auth.uid() and exists(select 1 from public.projects p where p.id=project_id and public.is_organization_member(p.organization_id)));
